FROM yilutech/node:14-alpine AS builder

LABEL stage="build"

COPY . /apps

RUN cd /apps \
 && npm config set registry https://registry.npm.taobao.org \
 && npm config set sass_binary_site https://npm.taobao.org/mirrors/node-sass/ \
 && npm install \
 && tar czf /node_modules.tar.gz --exclude="./node_modules/\@yilu-tech" ./node_modules \
 && cd / \
 && wget 'https://jiayu-dev.oss-cn-beijing.aliyuncs.com/uieditor.tar.gz' \
 && ls -alh node_modules.tar.gz

FROM yilutech/node:14-alpine

COPY --from=builder /node_modules.tar.gz /uieditor.tar.gz /

